# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: investment_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'investment_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18investment_service.proto\x12\tandisbank\"4\n\x1eGetInvestmentsByAccountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"a\n\x1fGetInvestmentsByAccountResponse\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12*\n\x0binvestments\x18\x02 \x03(\x0b\x32\x15.andisbank.Investment\"\x17\n\x15GetInvestmentsRequest\"M\n\x16GetInvestmentsResponse\x12\x33\n\x14possible_investments\x18\x01 \x03(\x0b\x32\x15.andisbank.Investment\"J\n\rInvestRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x15\n\rinvestment_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"L\n\x0eInvestResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12)\n\ninvestment\x18\x02 \x01(\x0b\x32\x15.andisbank.Investment\"6\n\nInvestment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x32\x9b\x02\n\x11InvestmentService\x12p\n\x17GetInvestmentsByAccount\x12).andisbank.GetInvestmentsByAccountRequest\x1a*.andisbank.GetInvestmentsByAccountResponse\x12U\n\x0eGetInvestments\x12 .andisbank.GetInvestmentsRequest\x1a!.andisbank.GetInvestmentsResponse\x12=\n\x06Invest\x12\x18.andisbank.InvestRequest\x1a\x19.andisbank.InvestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'investment_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETINVESTMENTSBYACCOUNTREQUEST']._serialized_start=39
  _globals['_GETINVESTMENTSBYACCOUNTREQUEST']._serialized_end=91
  _globals['_GETINVESTMENTSBYACCOUNTRESPONSE']._serialized_start=93
  _globals['_GETINVESTMENTSBYACCOUNTRESPONSE']._serialized_end=190
  _globals['_GETINVESTMENTSREQUEST']._serialized_start=192
  _globals['_GETINVESTMENTSREQUEST']._serialized_end=215
  _globals['_GETINVESTMENTSRESPONSE']._serialized_start=217
  _globals['_GETINVESTMENTSRESPONSE']._serialized_end=294
  _globals['_INVESTREQUEST']._serialized_start=296
  _globals['_INVESTREQUEST']._serialized_end=370
  _globals['_INVESTRESPONSE']._serialized_start=372
  _globals['_INVESTRESPONSE']._serialized_end=448
  _globals['_INVESTMENT']._serialized_start=450
  _globals['_INVESTMENT']._serialized_end=504
  _globals['_INVESTMENTSERVICE']._serialized_start=507
  _globals['_INVESTMENTSERVICE']._serialized_end=790
# @@protoc_insertion_point(module_scope)
